### ISSUE TITLE
Station Visualization and Interaction Design

### ISSUE THREAD

**Issue by mosoriob** [mosoriob/evan-visualization#13]
## Overview
Design and implement visualization system for both fixed and mobile stations with appropriate interaction patterns for each type.

### Fixed Stations
1. Visualization
   - Fixed marker on map
   - Status indicator (active/inactive)
   - Visual indication of sensor types
   - Clear indication of data collection frequency

2. Interaction
   - Hover for quick summary
   - Click for detailed view
   - Clustering for dense areas
   - Filter by sensor type/status

### Mobile Stations (Vehicles)
1. Route Visualization
   - Route path as vector line
   - Start/end points
   - Direction indicators
   - No measurement values on route

2. Interaction
   - Hover route for station summary
   - Support for multiple sensors
   - Historical route patterns
   - Collection frequency indicators

### Map Interface
1. Base Features
   - Multiple base layers
   - Layer controls
   - Zoom/pan functionality
   - Scale indicator
   - Legend

2. Filtering
   - By station type
   - By sensor type
   - By status
   - By time period

![Station Map User Journey](https://github.com/user-attachments/assets/41e0f76f-95d6-42c7-91d8-05335646e6d0)

### API Endpoints
1. Station List
```http
GET /campaign/{campaign_id}/station
Response includes both fixed and mobile stations
```

2. Station Details
```http
GET /campaign/{campaign_id}/station/{station_id}
Different response structure for fixed vs mobile
```

3. Mobile Station Routes
```http
GET /campaign/{campaign_id}/station/{station_id}/route
Only for mobile stations
```

### Performance Optimizations
1. Fixed Stations
   - Cluster markers in dense areas
   - Load details on demand
   - Cache station metadata

2. Mobile Stations
   - Simplified route geometries
   - No measurement value loading
   - Route caching

### Progressive Loading
```javascript
const loadingStrategy = {
  initial: {
    fixed: ['location', 'status', 'type'],
    mobile: ['routeOverview', 'status']
  },
  onDemand: {
    fixed: ['sensorDetails', 'recentReadings'],
    mobile: ['routeDetails', 'collectionMetadata']
  }
}
```

### Phase 1: Basic Visualization
- [ ] Fixed station markers
- [ ] Mobile station routes
- [ ] Basic hover interactions
- [ ] Simple filtering

### Phase 2: Enhanced Features
- [ ] Advanced filtering
- [ ] Clustering
- [ ] Detailed station views
- [ ] Performance optimizations

## Questions to Resolve
1. Visualization
   - Best way to distinguish station types
   - Handling overlapping routes/markers
   - Optimal clustering thresholds

2. Performance
   - Maximum stations per view
   - Route simplification levels
   - Caching strategies

3. UX
   - Information hierarchy in summaries
   - Filter interface design
   - Interaction patterns

## Acceptance Criteria
- [ ] Clear distinction between station types
- [ ] Efficient station summary display
- [ ] Smooth performance with many stations
- [ ] Proper error handling
- [ ] Accessible interface

## Dependencies
- Mapping library
- State management solution
- UI component library
- Backend API support

Please comment with:
- Visualization suggestions
- Performance optimization ideas
- Additional use cases

/cc @frontend-team @ux-team @backend-team
